### ISSUE TITLE
 [Errno 2] No such file or directory: 'data/CNN_NYT/processed/dict.src.txt'

### ISSUE THREAD

**Issue by hokiwood-geek** [jind11/TitleStylist#3]

**Comment by hokiwood-geek** [comment]
it appears when I run the .sh.

**Comment by HaleyQH** [comment]
I meet the same problem, have you fixed it?

**Comment by lulu867** [comment]
I came across the same problem. Have you found the solution?

**Comment by lulu867** [comment]
I have solved the problem.
Run data_process.sh first and ensure all the module installed.
