### ISSUE TITLE
Do you have the pretrained model?

### ISSUE THREAD

**Issue by stayaKotov** [jind11/TitleStylist#8]
I downloaded MASS model
Trying thing like that
 ./evaluate_mix_CNN_NYT_X.sh --style clickbait --model_dir ./pretrained_model
but get error: OSError: Model file not found: ./pretrained_model/checkpoint_best.pt
I agree with that, but where can I get the checkpoint for correct model?

Thank you and have a nice day!%)

**Comment by jind11** [comment]
hi, thanks for posting this question. When you want to perform evaluation, you need to first fine-tune the MASS model on your data using train_mix_CNN_NYT_X.sh so that you can get the checkpoint_best.pt file.
